### ISSUE TITLE
attach() doesn't work on Windows

### ISSUE THREAD

**Issue by rhysd** [neovim/node-client#10]
I tried the sample code in README but it didn't work.  When executing `$node sample.js`, it finished silently.

While I was investigating this issue with inserting `console()`,  I saw below `EPIPE` error (but it did not always occur).

```
Error: write EPIPE
    at exports._errnoException (util.js:856:11)
    at Socket._writeGeneric (net.js:675:26)
    at Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Socket.Writable.write (_stream_writable.js:207:11)
    at Socket.write (net.js:618:40)
    at Encoder.ondata (C:\Users\xxx\Tmp\node_modules\readable-stream\lib\_stream_readable.js:572:20)
    at emitOne (events.js:77:13)
    at Encoder.emit (events.js:169:7)
```

I confirmed that spawning `nvim` process was OK.  And requesting `vim_get_api_info` in `attach()` never executed its callback.

- Environment
  - Windows 8.1
  - Neovim nightly (got from AppVeyor result)
  - Node.js 5.4.1

**Comment by rhysd** [comment]
This may occur because of https://github.com/neovim/neovim/issues/4146.

**Comment by rhysd** [comment]
It was a problem of my environment.  Sorry.
