### ISSUE TITLE
:checkhealth Command Error issue

### ISSUE THREAD

**Issue by MithicSpirit** [neovim/node-client#147]
Running `:checkhealth` in neovim returns a command error and tells me to report the issue with the output of `/usr/local/bin/neovim-node-host --version`:
```js
/usr/local/lib/node_modules/neovim/node_modules/@msgpack/msgpack/dist/Decoder.js:85
        for await (const buffer of stream) {
            ^^^^^

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/neovim/node_modules/@msgpack/msgpack/dist/decode.js:3:19)
```

**Comment by MithicSpirit** [comment]
had wrong version of node installed
