### ISSUE TITLE
Nodejs Provider Command Error using NVM different versions

### ISSUE THREAD

**Issue by joaquinalcerro** [neovim/node-client#149]
Hi everyone, thanks in advance for the help.

This is my scenario:
FreeBSD 12.1 Release
NVM: 0.35.3
NVM installed node versions: v6.17.0 and v12.6.0
neovim: v0.4.3

I want neovim to use node v12.6.0 so I changed nvm to use it an installed the neovim client

`npm install -g neovim
`

Now I have a neovim-node-host like this:
```
➜  ~ ll /usr/home/jalcerro/.config/nvm/versions/node/v12.6.0/bin
total 82816
lrwxr-xr-x  1 jalcerro  jalcerro    37B Apr 11 15:52 neovim-node-host -> ../lib/node_modules/neovim/bin/cli.js
-rwxr-xr-x  1 jalcerro  jalcerro    40M Apr  3 20:38 node
lrwxr-xr-x  1 jalcerro  jalcerro    38B Apr  3 20:38 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxr-xr-x  1 jalcerro  jalcerro    38B Apr  3 20:38 npx -> ../lib/node_modules/npm/bin/npx-cli.js
➜  ~

```

I need to use the v6.17.0 for a specific project so I changed nvm to use it. Then, I open nvim and run checkhealth and got this error:

```
## Node.js provider (optional)
  - INFO: Node.js: v6.17.1
  - INFO: Neovim node.js host: /usr/home/jalcerro/.config/nvm/versions/node/v12.6.0/bin/neovim-node-host
  - ERROR: Command error (job=14, exit code 1): `node '/usr/home/jalcerro/.config/nvm/versions/node/v12.6.0/bin/neovim-node-host' --version` (in '/usr/home/jalcerro')
    Output: /usr/home/jalcerro/.config/nvm/versions/node/v12.6.0/lib/node_modules/neovim/node_modules/@msgpack/msgpack/dist/Decoder.js:82    async decodeSingleAsync(stream)
    {          ^^^^^^^^^^^^^^^^^SyntaxError: Unexpected identifier    at createScript (vm.js:56:10)    at Object.runInThisContext (vm.js:97:10)    at Module._compile (module.    js:549:28)    at Object.Module._extensions..js (module.js:586:10)    at Module.load (module.js:494:32)    at tryModuleLoad (module.js:453:12)    at Function.Module._load
    (module.js:445:3)    at Module.require (module.js:504:17)    at require (internal/module.js:20:19)    at Object.<anonymous> (/usr/home/jalcerro/.config/nvm/versions/node/    v12.6.0/lib/node_modules/neovim/node_modules/@msgpack/msgpack/dist/decode.js:3:19)
    Stderr: /usr/home/jalcerro/.config/nvm/versions/node/v12.6.0/lib/node_modules/neovim/node_modules/@msgpack/msgpack/dist/Decoder.js:82    async decodeSingleAsync(stream)
    {          ^^^^^^^^^^^^^^^^^SyntaxError: Unexpected identifier    at createScript (vm.js:56:10)    at Object.runInThisContext (vm.js:97:10)    at Module._compile (module.    js:549:28)    at Object.Module._extensions..js (module.js:586:10)    at Module.load (module.js:494:32)    at tryModuleLoad (module.js:453:12)    at Function.Module._load
    (module.js:445:3)    at Module.require (module.js:504:17)    at require (internal/module.js:20:19)    at Object.<anonymous> (/usr/home/jalcerro/.config/nvm/versions/node/    v12.6.0/lib/node_modules/neovim/node_modules/@msgpack/msgpack/dist/decode.js:3:19)
  - ERROR: Failed to run: ['node', '/usr/home/jalcerro/.config/nvm/versions/node/v12.6.0/bin/neovim-node-host', '--version']
    - ADVICE:node '/usr/home/jalcerro/.config/nvm/versions/node/v12.6.0/bin/neovim-node-host' --versionnode '/usr/home/jalcerro/.config/nvm/versions/node/v12.6.0/bin/neovim-
    node-host' --version
      - Report this issue with the output of:
      - ['node', '/usr/home/jalcerro/.config/nvm/versions/node/v12.6.0/bin/neovim-node-host', '--version']

```
But if I change nvm to use v12.6.0 the error goes away.

My question is: can I run neovim with version v12.6.0 with neovim-node-host and my project with v6.17.0? Will neovim work fine even it that error show up... I can't upgrade my project to a newer version of node.

Thanks for your comments. Best regards,

**Comment by rhysd** [comment]
install neovim package after switching to v6. this is matter of nvm usage, not related to this package. closing
