### ISSUE TITLE
(@next) - cannot find module '../lib/host'

### ISSUE THREAD

**Issue by dlants** [neovim/node-client#29]
Trying to follow the install instructions here https://github.com/neovim/node-client/tree/next

I get this:
```
function remote#define#AutocmdBootstrap[1]..remote#host#Require[10]..provider#node#Require, line 22
Vim(if):ch 2 was closed by the client
module.js:487
    throw err;
    ^
Error: Cannot find module '../lib/host'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/neovim/bin/cli.js:2:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
Error detected while processing function remote#define#AutocmdBootstrap[1]..remote#host#Require[10]..provider#node#Require:
line   32:
E605: Exception not caught: Failed to load node host. You can try to see what happened by starting nvim with $NVIM_NODE_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
Error detected while processing function remote#define#AutocmdBootstrap[1]..remote#host#Require:
line   10:
E171: Missing :endif
```
I am running with `$NVIM_NODE_LOG_FILE` but nothing gets sent there.

**Comment by billyvg** [comment]
Sorry, try installing @3.2.6

(npm by default uses your gitignore if no npmignore file is found...)
