### ISSUE TITLE
Error Running README Sample 

### ISSUE THREAD

**Issue by balajeerc** [neovim/node-client#32]
After installing node-host, after installing neovim@next, I get the following errors when running the sample on README. Tested with node version 7.5.0 as well as 8.0.0.

```
const nvim = await attach({ proc: nvim_proc });
                   ^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
```
Am I doing something wrong?

**Comment by billyvg** [comment]
Ah the README is wrong sorry - you need to wrap the entire code block in an IIFE because of how async/await works.

```
(async function() {
})();
```
