### ISSUE TITLE
 neovim module SyntaxError: Unexpected token '?' in cli.js

### ISSUE THREAD

**Issue by ubuntupunk** [neovim/node-client#373]
nvim checkhealth reports this error, and requests a report to maintainer.

```
node /usr/local/lib/node_modules/neovim/bin/cli.js 
/usr/local/lib/node_modules/neovim/bin/cli.js:18
const nodeMajorVersion = Number.parseInt(nodeMajorVersionStr ?? '0')
                                                              ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
➜  ~ node /usr/local/lib/node_modules/neovim/bin/cli.js --version
/usr/local/lib/node_modules/neovim/bin/cli.js:18
const nodeMajorVersion = Number.parseInt(nodeMajorVersionStr ?? '0')
                                                              ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by justinmk** [comment]
what version of node do you have?

I'll push a fix though.
