### ISSUE TITLE
No error log when set NVIM_NODE_LOG_LEVEL to error

### ISSUE THREAD

**Issue by chemzqm** [neovim/node-client#60]
When I set NVIM_NODE_LOG_LEVEL to debug, I can get the log of `debug` `info` `error` as expected, but if I change the NVIM_NODE_LOG_LEVEL to error, I get nothing at all.

Could anyone confirm that?

**Comment by carlosrocha** [comment]
How are you logging that? I tried setting the log level to error and only see the messages that are logged with `console.error`.

**Comment by chemzqm** [comment]
Oh, I found out node-client use info for plugin error on `:UpdateRemotePlugins`,  I think that this kind of error should be logged as error and notify the user plugin failed to regist.

```
2018-05-16T13:05:07.223Z - info: [plug.nvim] Error loading child ChildPlugin /Users/chemzqm/vim-dev/plug.nvim
2018-05-16T13:05:07.224Z - info: [plug.nvim] Error: wtf
    at Object.<anonymous> (/Users/chemzqm/vim-dev/plug.nvim/lib/index.js:61:7)
    at Module._compile (/Users/chemzqm/lib/node-client/lib/host/factory.js:49:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at Object.sandboxRequire [as require] (/Users/chemzqm/lib/node-client/lib/host/factory.js:79:46)
    at createPlugin (/Users/chemzqm/lib/node-client/lib/host/factory.js:103:39)
    at Object.loadPlugin (/Users/chemzqm/lib/node-client/lib/host/factory.js:118:16)

```
