### ISSUE TITLE
Calling API after UI attaching occurs an error.

### ISSUE THREAD

**Issue by rhysd** [neovim/node-client#8]
Hi, I'm making neovim GUI frontend with node.js.

Please see below test code.

```javascript
var cp = require('child_process');
var attach = require('.');

var nvim_proc = cp.spawn('nvim', ['-u', 'NONE', '-N', '--embed'], {});
attach(nvim_proc.stdin, nvim_proc.stdout, function(err, nvim) {
  nvim.on('request', function(method, args, resp) {
    console.log('request', method, args, resp);
  });

  nvim.on('notification', function(method, args) {
    console.log('notification', method, args);
  });

  nvim.on('disconnect', function() {
    console.log('disconnected');
  });

  nvim.uiAttach(80, 24, true, function() {
    nvim.getBuffers(function(err, bufs){
        if (err) {
            console.error(err);
            return;
        }
        console.log(bufs[0]);
    });
  });
});
```

After UI attaching, some APIs (here, I used `getBuffers` as example) fail with below error.

```
TypeError: this.slice(...)[m] is not a function
    at BufferList.(anonymous function) [as readUInt8] (/Users/rhayasd/Dev/github.com/neovim/node-client/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/bl/bl.js:210:58)
    at tryDecode (/Users/rhayasd/Dev/github.com/neovim/node-client/node_modules/msgpack5rpc/node_modules/msgpack5/index.js:219:21)
    at Object.decode (/Users/rhayasd/Dev/github.com/neovim/node-client/node_modules/msgpack5rpc/node_modules/msgpack5/index.js:203:18)
    at Decoder.decodeWithoutHeader [as _transform] (/Users/rhayasd/Dev/github.com/neovim/node-client/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:79:32)
    at Decoder.decodeWithoutHeader [as _transform] (/Users/rhayasd/Dev/github.com/neovim/node-client/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:91:10)
    at Decoder.Transform._read (/Users/rhayasd/Dev/github.com/neovim/node-client/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Decoder.Transform._write (/Users/rhayasd/Dev/github.com/neovim/node-client/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/rhayasd/Dev/github.com/neovim/node-client/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/Users/rhayasd/Dev/github.com/neovim/node-client/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at Decoder.Writable.write (/Users/rhayasd/Dev/github.com/neovim/node-client/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_writable.js:211:11)
```

I'm in trouble with this error because my frontend can't get the information from neovim while UI attaching.  (Of course many UI notifications are sent from neovim, but I want more information about buffers, windows and tabs to improve frontend behavior.)

I tried to fix this issue, but I couldn't because the error occured deeply inside the depended libraries.

My environment is below:

- OS X 10.11
- node.js 4.1.0 or Electron v0.34.2

**Comment by snoe** [comment]
I'm also seeing this, my npm list is 
```
└─┬ neovim-client@1.0.5
  ├── lodash@3.10.1
  ├─┬ msgpack5rpc@1.0.1
  │ └─┬ msgpack5@1.6.0
  │   ├─┬ bl@0.9.4
  │   │ └─┬ readable-stream@1.0.33
  │   │   ├── core-util-is@1.0.1
  │   │   ├── isarray@0.0.1
  │   │   └── string_decoder@0.10.31
  │   ├── inherits@2.0.1
  │   └─┬ readable-stream@1.1.13
  │     ├── core-util-is@1.0.1
  │     ├── isarray@0.0.1
  │     └── string_decoder@0.10.31
  └── traverse@0.6.6```

on node version 4.2.2 and 0.12 and os x 10.9

**Comment by nhynes** [comment]
Yeah, this one is way down there. It looks like an errant string is getting put where a Buffer should go (in bl.js). Unfortunately, I don't have the time to take a deep dive into this right now, but if you're interested in debugging (or when I get back to this), a good place to start is on line 114 of `bl.js`. 
Right before the error, `this._bufs` will contain a single string; I'm not yet sure how it got there and turning it into a Buffer causes an EPIPE.

**Comment by snoe** [comment]
The offending code seems to be here https://github.com/neovim/node-client/blob/master/index.js#L17-L21 - before and after the traverse you can run this and see that _bufs goes from a Buffer to a string.
```
if (obj[0] && obj[0]._session)
    console.log(obj[0]._session._decoder._chunks._bufs);
```

I expect obj shouldn't have those fields at this point. I'll work on a patch for this.
