### ISSUE TITLE
Node.js provider Error with `:checkHealth`

### ISSUE THREAD

**Issue by yacoolto** [neovim/node-client#92]
Hi.
I'm using ndenv, and I want to use node-client.
Simply, I installed neovim npm package to global,
then added `let g:node_host_prog = expand($NDENV_ROOT . '/shims/neovim-node-host')` to init.vim.
However, run `:checkHealth`, always shows that message.

```vim
## Node.js provider (optional)
  - INFO: Node.js: v10.6.0
  - INFO: Neovim node.js host: /Users/yacoolto/Develop/github.com/riywo/anyenv/envs/ndenv/shims/neovim-node-host
  - ERROR: Command error (job=16): `node /Users/yacoolto/Develop/github.com/riywo/anyenv/envs/ndenv/shims/neovim-node-host --version` (in '/Users/yacoolto')
    Output: /Users/yacoolto/Develop/github.com/riywo/anyenv/envs/ndenv/shims/neovim-node-host:3[ -n "$NDENV_DEBUG" ] && set -x     ^^^^^^^^^^^^^^SyntaxError: Unexpected string    at new Script (vm.js:51:7)    at createScript (vm.js:138:10)    at Object.runInThisContext (vm.js:199:10)    at Module._compile (module.js:626:28)    at Object.Module._extensions..js (module.js:673:10)    at Module.load (module.js:575:32)    at tryModuleLoad (module.js:515:12)    at Function.Module._load (module.js:507:3)    at Function.Module.runMain (module.js:703:10)    at startup (bootstrap_node.js:193:16)
  - ERROR: Failed to run: ['node', '/Users/yacoolto/Develop/github.com/riywo/anyenv/envs/ndenv/shims/neovim-node-host', '--version']
    - ADVICE:
      - Report this issue with the output of: 
      - ['node', '/Users/yacoolto/Develop/github.com/riywo/anyenv/envs/ndenv/shims/neovim-node-host', '--version']
```

Following that ADVICE, I tried `node $NDENV_ROOT/shims/neovim-node-host --version`, it failed with same error.

```bash
$ node $NDENV_ROOT/shims/neovim-node-host --version
/Users/yacoolto/Develop/github.com/riywo/anyenv/envs/ndenv/shims/neovim-node-host:3
[ -n "$NDENV_DEBUG" ] && set -x
     ^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:626:28)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
```

In contrast, `$NDENV_ROOT/shims/neovim-node-host --version` shows `4.2.1` without errors.
That's why? Is there anything wrong?

**Comment by chemzqm** [comment]
`neovim-node-host` is executable, but can't be invoked by `node {filename}`.
So you should use `let g:node_host_prog=/path/to/neovim/bin/cli.js` in your `.vimrc`

**Comment by martin-braun** [comment]
@chemzqm The `neovim-node-host` "binary" is just a link to its `cli.js`, so `vim.g.node_host_prog = "..../bin/neovim-node-host"` was the way to go for me.
